# Generated by Django 5.2.10 on 2026-01-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_invoice_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="gst_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
